name: Playwright Test Template
on:
  workflow_call:

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Cache pipenv virtualenv
      uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      run: |
        pipenv install --dev

    - name: Install Playwright Chromium
      run: |
        pipenv run playwright install chromium
        pipenv run playwright install-deps chromium

    - name: Install gettext
      run: sudo apt-get install -y gettext

    - name: Compile translation messages
      run: |
        msgfmt -o locales/de/LC_MESSAGES/lokalise.mo locales/de/LC_MESSAGES/lokalise.po
        msgfmt -o locales/en/LC_MESSAGES/lokalise.mo locales/en/LC_MESSAGES/lokalise.po
        msgfmt -o locales/es/LC_MESSAGES/lokalise.mo locales/es/LC_MESSAGES/lokalise.po
        msgfmt -o locales/fr/LC_MESSAGES/lokalise.mo locales/fr/LC_MESSAGES/lokalise.po
        msgfmt -o locales/it/LC_MESSAGES/lokalise.mo locales/it/LC_MESSAGES/lokalise.po
        msgfmt -o locales/nl/LC_MESSAGES/lokalise.mo locales/nl/LC_MESSAGES/lokalise.po

    - name: Run Playwright tests
      run: |
        pipenv run pytest tests/

    - name: Upload test results
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: playwright-test-results
        path: |
          test-results/
          playwright-report/
        retention-days: 5

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: ${{ !cancelled() }}
      with:
        files: "test-results/junit.xml"