name: Scheduled Playwright Tests
on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  playwright_tests:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/playwright_template.yml
