name: PR Playwright Tests
on:
  pull_request:
    branches: [ feature/*, fix/* ]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  playwright_tests:
    uses: ./.github/workflows/playwright_template.yml
